name: Honkit test

on: 
  push:
    branches: [ 'main' ]
    tags: [ 'v*.*', 'v*.*.*', 'v*.*.*-*' ]


jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ "18.x" ]
    steps:
    - uses: actions/checkout@v2
    env:
      DEPLOY: ${{ secrets.SSH_PRIVATE_KEY }}

    if: env.DEPLOY != ''
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
    if: env.DEPLOY != ''
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: install calibre
      run: sudo apt-get update && sudo apt -y install calibre

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install node deps
      run: npm -y install

    - name: honkit build
      run: |
        npx -y honkit build
        npx -y honkit pdf
        npx -y honkit epub
        npx -y honkit mobi
    if: env.DEPLOY != ''
    - name: Deploy with rsync
      run: |
        mv book.pdf _book
        mv book.epub _book
        mv book.mobi _book
        chmod +r _book/book.pdf _book/book.epub _book/book.mobi
        cd _book
        rsync -r --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/doc.openxeco.org/

    # prepare release
    - name: Get repository name
      id: repository
      run: echo "::set-output name=pathref::$(echo '${{ github.repository }}' | cut -d'/' -f2)-$(echo '${{ github.ref_name }}' | sed 's/[^[:alnum:]\.-]/_/g')"

    - name: create artifact archive
      run: |
        tar -zcf ${{ steps.repository.outputs.pathref }}.tar.gz book.pdf book.epub book.mobi

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.repository.outputs.pathref }}.tar.gz
        fail_on_unmatched_files: true
      if: startsWith(github.ref, 'refs/tags/')

