name: Honkit test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
        - uses: actions/checkout@v3
          with:
            ref: main

        - name: Install honkit and dependencies
          run: |
              sudo apt -y install libgif-dev calibre npm nodejs
              sudo npm config set strict-ssl false
              sudo npm cache clean -f
              npm install honkit
        - name: Install plugin-github
          run: |
              npm install gitbook-plugin-github
        - name: Install plugin-atoc
          run: |
              npm install gitbook-plugin-atoc
        - name: Install plugin-anchors
          run: |
              npm install gitbook-plugin-anchors
        - name: Install plugin-alerts
          run: |
              npm install gitbook-plugin-alerts
        - name: Install plugin-search
          run: |
              npm install gitbook-plugin-search
        - name: Install plugin-gist
          run: |
              npm install gitbook-plugin-gist
        - name: Install plugin-image-class
          run: |
              npm install gitbook-plugin-image-class
        - name: Install plugin-codesnippet
          run: |
              npm install gitbook-plugin-codesnippet
        - name: Install plugin-last-modified
          run: |
              npm install gitbook-plugin-last-modified
        - name: Install plugin-fontsettings
          run: |
              npm install gitbook-plugin-fontsettings
        - name: Install plugin-sitemap
          run: |
              npm install gitbook-plugin-sitemap
        - name: Install plugin-advanced-emoji
          run: |
              npm install gitbook-plugin-advanced-emoji
        - name: Run honkit build
          run: |
              npx honkit build
        - name: Run honkit epub
          run: |
              npx honkit epub
        - name: Run honkit mobi
          run: |
              npx honkit mobi
        - name: Run pdf converter
          run: |
              ebook-convert book.epub book.pdf
